runtime: python310
instance_class: F2

entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /images
  static_dir: static/images

env_variables:
  MYSQL_HOST: 35.209.13.18
  MYSQL_USER: g41v1rj
  MYSQL_PASSWORD: 000000
  MYSQL_DATABASE: neushop
